### ISSUE TITLE
Rename `requestExample.TXT` to `requestExample.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [kirillkuks/Maps#1]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by kirillkuks** [comment]
I have no idea how you find this weird repository :)
I renamed requestExample.txt to requestExample.overpassql. I hope it will help you to get from GitHub supporting overpassql file extension.

P. S.
This file should have been temporary and i was planning to remove it. But now i will save it :)

**Comment by FloEdelmann** [comment]
I found it using GitHub's [new code search](https://github.blog/2022-11-15-a-better-way-to-search-navigate-and-understand-code-on-github/) using the query [`/\[out:(json|xml)\]/ -path:/\.(overpassql|asciidoc|astro|c|cljs?|coffee|cpp|cs|ctp|cxx|dart|elm|es6|fold|fs|go|gs|h|html?|ipynb|java|jl|jsonc?|jsx?|kt|log|lr|m|m?xml|model3|module|nim|nix|php|pins|pl|pyt?|q?md|qml|qgs|r|rb|rd|rmd|rs|rst|scala|sh|sql|st|suma|svelte|swift|tex|tsx?|vue|ya?ml)$/ -path:Makefile -path:log.txt -path:okhttp -path:addr-osmify -path:web_journey -path:todo.txt -path:tuesday-1800`](https://github.com/search?q=%2F%5C%5Bout%3A(json%7Cxml)%5C%5D%2F%20-path%3A%2F%5C.(overpassql%7Casciidoc%7Castro%7Cc%7Ccljs%3F%7Ccoffee%7Ccpp%7Ccs%7Cctp%7Ccxx%7Cdart%7Celm%7Ces6%7Cfold%7Cfs%7Cgo%7Cgs%7Ch%7Chtml%3F%7Cipynb%7Cjava%7Cjl%7Cjsonc%3F%7Cjsx%3F%7Ckt%7Clog%7Clr%7Cm%7Cm%3Fxml%7Cmodel3%7Cmodule%7Cnim%7Cnix%7Cphp%7Cpins%7Cpl%7Cpyt%3F%7Cq%3Fmd%7Cqml%7Cqgs%7Cr%7Crb%7Crd%7Crmd%7Crs%7Crst%7Cscala%7Csh%7Csql%7Cst%7Csuma%7Csvelte%7Cswift%7Ctex%7Ctsx%3F%7Cvue%7Cya%3Fml)%24%2F%20-path%3AMakefile%20-path%3Alog.txt%20-path%3Aokhttp%20-path%3Aaddr-osmify%20-path%3Aweb_journey%20-path%3Atodo.txt%20-path%3Atuesday-1800&type=code).

Thanks for renaming!
